/*
 * To change this license header, choose License Headers in Project Properties. To change this
 * template file, choose Tools | Templates and open the template in the editor.
 */
package com.app.form.pembelian;

import com.app.dao.BarangDAO;
import com.app.dao.PembelianDAO;
import com.app.dao.PembelianRinciDAO;
import com.app.dao.PembelianSmtDAO;
import com.app.model.ModelBarang;
import com.app.model.ModelPembelian;
import com.app.model.ModelPembelianRinci;
import com.app.model.ModelPembelianSmt;
import com.app.model.ModelUser;
import com.app.service.ServiceBarang;
import com.app.service.ServicePembelian;
import com.app.service.ServicePembelianRinci;
import com.app.service.ServicePembelianSmt;
import com.app.tablemodel.TableModelBarang;
import com.app.tablemodel.TableModelPembelian;
import com.app.tablemodel.TableModelPembelianRinci;
import com.app.tablemodel.TableModelPembelianSmt;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Acer
 */
public class FormRincianPembelian extends javax.swing.JDialog {

    private final TableModelPembelianRinci tblModel = new TableModelPembelianRinci();
    private final TableModelPembelian tblP = new TableModelPembelian();

    private ServicePembelianRinci servisPR = new PembelianRinciDAO();
    private ServicePembelian servisP = new PembelianDAO();
    private ServiceBarang servisBarang = new BarangDAO();

    private String idBarang;
    private String idKasir;
    private Timer timer;
    private ModelPembelian mp = new ModelPembelian();
    String id = "";

    /**
     * Creates new form frmCariBarang
     */
    public FormRincianPembelian(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
//        nonAktif();
        btnCari.setEnabled(true);
//        btnDetail.setEnabled(true);
        txtBarcode.setEditable(true);
        this.setLocationRelativeTo(null);
        this.id = id;
        tabel.setModel(tblModel);
        lbNoFak.setText(id);
        loadData();
    }

    private void loadData() {
        List<ModelPembelianRinci> list = servisPR.tampil_detail_P(id);
        tblModel.setData(list);
        List<ModelPembelian> listP = servisP.getAllData();
        tblP.setData(listP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lbNoFak = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        btnUpdateSmt = new javax.swing.JButton();
        btnHapusSmt = new javax.swing.JButton();
        btnBatalSmt = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new com.raven.swing.Table();
        txtRef = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setText("Rincian Pembelian");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Table Rincian Pembelian");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setText("No. REF :");

        lbNoFak.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbNoFak.setText("REF");

        jLabel8.setText("ID REF");

        jLabel9.setText("Nama");

        jLabel18.setText("Harga");

        jLabel10.setText("Satuan");

        jLabel11.setText("Qty");

        txtBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarcodeActionPerformed(evt);
            }
        });
        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyReleased(evt);
            }
        });

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        btnUpdateSmt.setText("UPDATE");
        btnUpdateSmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSmtActionPerformed(evt);
            }
        });

        btnHapusSmt.setText("HAPUS");
        btnHapusSmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusSmtActionPerformed(evt);
            }
        });

        btnBatalSmt.setText("BATAL");
        btnBatalSmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalSmtActionPerformed(evt);
            }
        });

        btnCari.setText("...");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        txtRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefActionPerformed(evt);
            }
        });
        txtRef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRefKeyReleased(evt);
            }
        });

        jLabel12.setText("Barcode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdateSmt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapusSmt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatalSmt)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lbNoFak)
                                .addGap(2, 2, 2))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCari))
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jLabel18))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jLabel10))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lbNoFak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel18)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateSmt)
                    .addComponent(btnHapusSmt)
                    .addComponent(btnBatalSmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarcodeActionPerformed

    private void txtBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyReleased
//        pencarianBarang();
    }//GEN-LAST:event_txtBarcodeKeyReleased

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        updateRincian();
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnUpdateSmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSmtActionPerformed
        updateRincian();
    }//GEN-LAST:event_btnUpdateSmtActionPerformed

    private void btnHapusSmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusSmtActionPerformed
        hapusRincian();
    }//GEN-LAST:event_btnHapusSmtActionPerformed

    private void btnBatalSmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalSmtActionPerformed
        loadData();
        resetForm();
    }//GEN-LAST:event_btnBatalSmtActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        pencarianObatFD();
    }//GEN-LAST:event_btnCariActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        dataTableRinci();        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void txtRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefActionPerformed

    private void txtRefKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRefKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
         * feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRincianPembelian.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRincianPembelian.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRincianPembelian.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRincianPembelian.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormRincianPembelian dialog = new FormRincianPembelian(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalSmt;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapusSmt;
    private javax.swing.JButton btnUpdateSmt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbNoFak;
    private com.raven.swing.Table tabel;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtRef;
    private javax.swing.JTextField txtSatuan;
    // End of variables declaration//GEN-END:variables
    private void dataTableRinci() {
        int row = tabel.getSelectedRow();
        txtRef.setText(tabel.getValueAt(row, 0).toString());
        txtBarcode.setText(tabel.getValueAt(row, 1).toString());
        txtNama.setText(tabel.getValueAt(row, 3).toString());
        txtHarga.setText(tabel.getValueAt(row, 7).toString());
        txtQty.setText(tabel.getValueAt(row, 5).toString());
        txtSatuan.setText(tabel.getValueAt(row, 6).toString());

        nonAktif();
        txtQty.setEditable(true);
        btnUpdateSmt.setEnabled(true);
        btnHapusSmt.setEnabled(true);
        btnBatalSmt.setEnabled(true);
    }

    private void resetForm() {
        btnCari.setEnabled(true);
        txtRef.setText("");
        txtBarcode.setText("");
        txtBarcode.requestFocus();
        txtNama.setText("");
        txtHarga.setText("");
        txtSatuan.setText("");
        txtQty.setText("");
    }

    private void nonAktif() {
        txtRef.setEditable(false);
        txtNama.setEditable(false);
        txtHarga.setEditable(false);
        txtSatuan.setEditable(false);
        txtQty.setEditable(false);
        btnCari.setEnabled(false);
        btnHapusSmt.setEnabled(false);
        btnUpdateSmt.setEnabled(false);
        btnBatalSmt.setEnabled(false);
    }
    
    public static String generateRandomID() {
        // Membuat objek Random
        Random random = new Random();

        // Menghasilkan angka acak 6 digit (antara 100000 dan 999999)
        int randomNumber = 100000 + random.nextInt(900000);

        // Menggabungkan prefix "RINC" dengan angka acak
        return "RINC" + randomNumber;
    }

    private void pencarianObatFD() {
        frmCariBarang modelForm = new frmCariBarang(null, true, "Transaksi");
        modelForm.setTitle("PILIH BARANG");
        modelForm.setVisible(true);

        if (modelForm.modelDialog.getBarcode() != null) {
//            System.out.println("Memilih"+ modelForm.modelDialog.getNama_barang());
//            String ref = generateId(lbNoFak.getText(),1);
            txtRef.setText(generateRandomID());
            idBarang = modelForm.modelDialog.getIdBarang();
            txtNama.setText(modelForm.modelDialog.getNama_barang());
            txtHarga.setText(modelForm.modelDialog.getHarga().toPlainString());
            txtSatuan.setText(modelForm.modelDialog.getSatuan());
            txtBarcode.setText(modelForm.modelDialog.getBarcode());

            String idPembelianrinci = txtRef.getText();
            String barcode = txtBarcode.getText();
            String namaProduk = txtNama.getText();
            BigDecimal harga = new BigDecimal(txtHarga.getText());
            String satuan = modelForm.modelDialog.getSatuan();
            int jumlah = 1;
            BigDecimal subTotal = harga.multiply(BigDecimal.valueOf(jumlah));

            boolean obatSudahAda = false;
            for (int i = 0; i < tblModel.getRowCount(); i++) {
                if (tblModel.getData(i).getModelBarang().getBarcode().equals(barcode)) {
                    obatSudahAda = true;
                    updateQty(i, harga, jumlah);
                    break;
                }
            }
            System.out.println("low");
            if (!obatSudahAda) {
                System.out.println("cek");
//                ModelPembelianSmt smt = new ModelPembelianSmt();
                ModelBarang pd = new ModelBarang();
                ModelPembelianRinci det = new ModelPembelianRinci();
                ModelPembelian mp = new ModelPembelian();
                
                mp.setIdPembelian(lbNoFak.getText());

                pd.setIdBarang(idBarang);
                pd.setBarcode(barcode);
                pd.setNama_barang(namaProduk);
                pd.setHarga(harga);
                pd.setSatuan(satuan);
                pd.setBarcode(barcode);

                det.setId(idPembelianrinci);
                det.setQty(jumlah);
                det.setNilai(subTotal);
                det.setModelPemb(mp);
                det.setModelBarang(pd);
//                det.setModelPembRinci(det);

                servisPR.tambah_detail_P(det);
                servisPR.sumTotal(det);
                loadData();
                resetForm();
                txtBarcode.setEditable(true);
                txtBarcode.setEnabled(true);
                btnCari.setEnabled(true);
            }
        } else {
            System.out.println("Anda tidak memilih produk!");
        }
    }

    private void updateQty(int rowIndex, BigDecimal harga, int jumlah) {
        ModelPembelianRinci det = tblModel.getData(rowIndex);
        double jumlahLama = det.getQty();
        double jumlahBaru = jumlahLama + jumlah;
        BigDecimal subtotal = harga.multiply(BigDecimal.valueOf(jumlahBaru));

        det.setQty(jumlahBaru);
        det.setNilai(subtotal);
        servisPR.updateData(det.getId(), det.getQty(), det.getModelBarang().getHarga());
        servisPR.sumTotal(det);

        
        loadData();
        tblModel.fireTableRowsUpdated(rowIndex, rowIndex);
        resetForm();
    }

    private void updateRincian() {
        if (!txtQty.getText().equals("")) {
            String ref = txtRef.getText();
            String barcode = txtBarcode.getText();
            String namaBarang = txtNama.getText();
            BigDecimal harga = new BigDecimal(txtHarga.getText().replace(",", ""));
            String satuan = txtSatuan.getText().replace(",", "");
            double jumlah = Double.parseDouble(txtQty.getText().replace(",", ""));
            BigDecimal subTotal = harga.multiply(BigDecimal.valueOf(jumlah));

            ModelBarang pd = new ModelBarang();
            ModelPembelianRinci det = new ModelPembelianRinci();

            pd.setIdBarang(idBarang);
            pd.setBarcode(barcode);
            pd.setNama_barang(namaBarang);
            pd.setHarga(harga);
            pd.setSatuan(satuan);

            det.setId(ref);
            det.setQty(jumlah);
            det.setNilai(subTotal);

            det.setModelBarang(pd);
//            det.setModelPembRinci(det);

            servisPR.updateData(det.getId(), det.getQty(), det.getModelBarang().getHarga());
            servisPR.sumTotal(det);

//            DecimalFormat df1 = new DecimalFormat("#,##0");
//            BigDecimal jumlahSubtotal = det.getNilai();
//            String totalNoDecimal = df1.format(jumlahSubtotal);
//            txtTotal.setText("Rp. " + totalNoDecimal);
//            
            loadData();
            resetForm();
            txtBarcode.setEnabled(true);
            txtBarcode.setEditable(true);
            btnCari.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Qty tidak boleh kosong!");
        }
    }

    private void hapusRincian() {
        int selectedRow = tabel.getSelectedRow();
        if (selectedRow >= 0) {
            // Konfirmasi penghapusan
            ModelPembelianRinci model = tblModel.getData(selectedRow); // Ambil data dari model tabel

            int confirm = JOptionPane.showConfirmDialog(null,
                    "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Hapus data dari database menggunakan ID
                boolean berhasil = servisPR.hapusData(tabel.getValueAt(selectedRow, 0).toString()); // Panggil DAO untuk hapus data
                if (berhasil) {
                    // Hapus data dari tabel sementara
                    tblModel.deleteData(selectedRow);
                    loadData(); // Muat ulang data ke tabel
                    resetForm(); // Reset form input
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                } else {
                    System.out.println(tabel.getValueAt(selectedRow, 0).toString());
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus.");
        }
    }
}
