/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.app.form.user;

import com.app.dao.UserDAO;
import com.app.model.ModelUser;
import com.app.service.ServiceUser;
import com.app.tablemodel.TableModelUser;
import com.formdev.flatlaf.FlatClientProperties;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Rohim
 */
public class FormInputUser extends javax.swing.JDialog {

    /**
     * Creates new form FormInputUser
     */
    private TableModelUser tblModel = new TableModelUser();
    private ServiceUser servis = new UserDAO();
    private ModelUser user;
    private int idUser;
    private int row;
    private FormUser formuser;

    public FormInputUser(java.awt.Frame parent, boolean modal, int row, ModelUser user, FormUser formuser) {
        super(parent, modal);
        this.user = user;
        this.row = row;
        this.formuser = formuser;
        initComponents();
        if (user != null) {
            dataTable();
        }
        loaddata();
        setLayoutForm();
    }

    private void setLayoutForm() {
        j_password.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true;"
                + "showCapsLock:true");

        txt_nama.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Nama");
        txt_rfid.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan RFID");
        txt_username.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Username");
        j_password.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Password");
        txt_notelp.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan No Telepon");
        txt_alamat.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Alamat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new com.raven.swing.ButtonGradient();
        btn_batal = new com.raven.swing.ButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        j_password = new javax.swing.JPasswordField();
        cb_role = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        txt_rfid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("MASTER > Manajemen Karyawan > Tambah");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM TAMBAH USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_simpan.setText("SIMPAN");
        btn_simpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Role");

        cb_role.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Role", "admin", "kasir", "gudang" }));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Nama");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Alamat");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("No Telepon");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("RFID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama)
                            .addComponent(txt_rfid)
                            .addComponent(txt_username)
                            .addComponent(j_password)
                            .addComponent(txt_notelp)
                            .addComponent(txt_alamat)
                            .addComponent(cb_role, 0, 240, Short.MAX_VALUE))
                        .addGap(0, 70, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rfid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_password, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (btn_simpan.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        if (btn_simpan.getText().equals("SIMPAN")) {
            resetForm();
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            dispose();
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormUser formuser = new FormUser();
                FormInputUser dialog = new FormInputUser(new javax.swing.JFrame(), true, 1, null, formuser);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ButtonGradient btn_batal;
    private com.raven.swing.ButtonGradient btn_simpan;
    private javax.swing.JComboBox<String> cb_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField j_password;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JTextField txt_rfid;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        List<ModelUser> list = servis.tampilData();
        tblModel.setData(list);
    }

    private void resetForm() {
        txt_nama.setText("");
        txt_username.setText("");
        j_password.setText("");
        txt_notelp.setText("");
        txt_alamat.setText("");
        cb_role.setSelectedIndex(0);
    }

    private boolean validasiInput() {
        boolean valid = false;

        if (txt_nama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Nama kosong");
        } else if (txt_username.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Username kosong");
        } else if (j_password.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Password kosong");
        } else if (cb_role.getSelectedItem().equals("Pilih Role")) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Role");
            System.out.println("Validasi gagal: Role belum dipilih");
        } else if (txt_notelp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telepon Tidak Boleh Kosong");
            System.out.println("Validasi gagal: No Telepon kosong");
        } else if (txt_alamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Alamat kosong");
        } else {
            valid = true;
        }

        return valid;
    }

    private void simpanData() {
        if (validasiInput()) {
            String nama = txt_nama.getText();
            String rfid = txt_rfid.getText();
            String username = txt_username.getText();
            String password = j_password.getText();
            String no_telepon = txt_notelp.getText();
            String alamat = txt_alamat.getText();
            String Role = cb_role.getSelectedItem().toString();

            ModelUser model = new ModelUser();
            model.setNama(nama);
            model.setRfidUid(rfid); // Gunakan RFID otomatis jika kosong
            model.setUsername(username);
            model.setPassword(password);
            model.setNo_telepon(no_telepon);
            model.setAlamat(alamat);
            model.setRole(Role);

            servis.tambahData(model); // Menambahkan data ke database
            tblModel.insertData(model); // Menambahkan data ke tabel model
            formuser.refreshTable(); // Menyegarkan tabel
            resetForm(); // Reset form input
            dispose(); // Menutup form
        }
    }

    private void dataTable() {
        btn_simpan.setText("PERBARUI");

        idUser = user.getIdUser();
        jLabel4.setVisible(false);
        j_password.setVisible(false);

        txt_nama.setText(user.getNama());
        txt_rfid.setText(user.getRfidUid());
        txt_username.setText(user.getUsername());
        txt_notelp.setText(user.getNo_telepon());
        txt_alamat.setText(user.getAlamat());
        cb_role.setSelectedItem(user.getRole());

        jLabel1.setText("MASTER > Manajemen Karyawan > Perbarui");
        jLabel2.setText("PERBARUI DATA KARYAWAN");
    }

    private void perbaruiData() {
        String nama = txt_nama.getText();
        String rfid = txt_rfid.getText(); // Tidak mengubah RFID yang sudah ada
        String username = txt_username.getText();
        String alamat = txt_alamat.getText();
        String no_telepon = txt_notelp.getText();
        String Role = cb_role.getSelectedItem().toString();

        ModelUser model = new ModelUser();
        model.setIdUser(idUser); // Pastikan ID sudah di-set
        model.setNama(nama);
        model.setRfidUid(rfid); // Jangan mengubah RFID
        model.setUsername(username);
        model.setNo_telepon(no_telepon);
        model.setAlamat(alamat);
        model.setRole(Role);

        servis.perbaruiData(model); // Perbarui data di database
        tblModel.updateData(row, model); // Perbarui data di tabel model
        resetForm(); // Reset form input
        dispose(); // Menutup form
    }

    public void setRole(String role) {
        if (cb_role.getItemCount() == 0) {
            cb_role.addItem("admin");
            cb_role.addItem("kasir");
            cb_role.addItem("gudang");
        }

        if (role == null || role.isEmpty()) {
            cb_role.setSelectedIndex(0); // Pilih default
        } else {
            cb_role.setSelectedItem(role); // Pilih sesuai data
        }
    }

//    private void generateRFIDOtomatis() {
//        UserDAO userDAO = new UserDAO();
//        String rfid = userDAO.generateRFID(); 
//        txt_rfid.setText(rfid);  
//        txt_rfid.setEditable(false); 
//    }
}
