/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.app.form.supplier;

import com.app.dao.SupplierDAO;
import com.app.model.ModelSupplier;
import com.app.service.ServiceSupplier;
import com.app.tablemodel.TableModelSupplier;
import com.formdev.flatlaf.FlatClientProperties;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Rohim
 */
public class FormInputSupplier extends javax.swing.JDialog {

    /**
     * Creates new form FormInputSupplier
     */
    private TableModelSupplier tblModel = new TableModelSupplier();
    private ServiceSupplier servis = new SupplierDAO();
    private ModelSupplier Supplier;
    private int idSupplier;
    private int row;
    private FormSupplier FormSupplier;

    public FormInputSupplier(java.awt.Frame parent, boolean modal, int row, ModelSupplier Supplier, FormSupplier FormSupplier) {
        super(parent, modal);
        this.Supplier = Supplier;
        this.row = row;
        this.FormSupplier = FormSupplier;
        initComponents();
        if (Supplier != null) {
            dataTable();
        }
        loaddata();
        setLayoutForm();
    }

    private void setLayoutForm() {
        

        txt_nama.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Nama");
        txt_notelp.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan No Telepon");
        txt_alamat.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Alamat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new com.raven.swing.ButtonGradient();
        btn_batal = new com.raven.swing.ButtonGradient();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("MASTER > Manajemen Karyawan > Tambah");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM TAMBAH USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_simpan.setText("SIMPAN");
        btn_simpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Nama");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Alamat");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("No Telepon");

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(txt_notelp)))
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(266, 266, 266))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (btn_simpan.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        if (btn_simpan.getText().equals("SIMPAN")) {
            resetForm();
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            dispose();
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormSupplier FormSupplier = new FormSupplier();
                FormInputSupplier dialog = new FormInputSupplier(new javax.swing.JFrame(), true, 1, null, FormSupplier);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ButtonGradient btn_batal;
    private com.raven.swing.ButtonGradient btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_notelp;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        List<ModelSupplier> list = servis.tampilData();
        tblModel.setData(list);
    }

    private void resetForm() {
        txt_nama.setText("");
        txt_notelp.setText("");
        txt_alamat.setText("");
    }

    private boolean validasiInput() {
        boolean valid = false;

        if (txt_nama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Nama kosong");
            System.out.println("Validasi gagal: Role belum dipilih");
        } else if (txt_notelp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telepon Tidak Boleh Kosong");
            System.out.println("Validasi gagal: No Telepon kosong");
        } else if (txt_alamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Alamat kosong");
        } else {
            valid = true;
        }

        return valid;
    }

    private void simpanData() {
        if (validasiInput()) {
            String nama = txt_nama.getText();
            String no_telepon = txt_notelp.getText();
            String alamat = txt_alamat.getText();

            ModelSupplier model = new ModelSupplier();
            model.setNama(nama);
            model.setNo_hp(no_telepon);
            model.setAlamat(alamat);

            servis.tambahData(model); // Menambahkan data ke database
            tblModel.insertData(model); // Menambahkan data ke tabel model
            FormSupplier.refreshTable(); // Menyegarkan tabel
            resetForm(); // Reset form input
            dispose(); // Menutup form
        }
    }

    private void dataTable() {
        btn_simpan.setText("PERBARUI");

        idSupplier = Supplier.getId_supplier();

        txt_nama.setText(Supplier.getNama());
        txt_notelp.setText(Supplier.getNo_hp());
        txt_alamat.setText(Supplier.getAlamat());

        jLabel1.setText("MASTER > Manajemen Karyawan > Perbarui");
        jLabel2.setText("PERBARUI DATA KARYAWAN");
    }

    private void perbaruiData() {
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        String no_telepon = txt_notelp.getText();

        ModelSupplier model = new ModelSupplier();
        model.setId_supplier(idSupplier); // Pastikan ID sudah di-set
        model.setNama(nama);
        model.setNo_hp(no_telepon);
        model.setAlamat(alamat);

        servis.perbaruiData(model); // Perbarui data di database
        tblModel.updateData(row, model); // Perbarui data di tabel model
        resetForm(); // Reset form input
        dispose(); // Menutup form
    }
}