/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.app.form.barang;

import com.app.dao.BarangDAO;
import com.app.form.barang.*;
import com.app.dao.UserDAO;
import com.app.model.ModelBarang;
import com.app.model.ModelUser;
import com.app.service.ServiceBarang;
import com.app.service.ServiceUser;
import com.app.tablemodel.TableModelBarang;
import com.app.tablemodel.TableModelUser;
import com.formdev.flatlaf.FlatClientProperties;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Rohim
 */
public class FormInputBarang extends javax.swing.JDialog {

    /**
     * Creates new form FormInputUser
     */
    private TableModelBarang tblModel = new TableModelBarang();
    private ServiceBarang servis = new BarangDAO();
    private ModelBarang barang;
    private int idBarang;
    private int row;
    private FormBarang formBarang;

    public FormInputBarang(java.awt.Frame parent, boolean modal, int row, ModelBarang barang, FormBarang formbarang) {
        super(parent, modal);
        this.barang = barang;
        this.row = row;
        this.formBarang = formBarang;
        initComponents();
        if (barang != null) {
            dataTable();
        }
        loaddata();
        setLayoutForm();
    }

    private void setLayoutForm() {
        txt_nama.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Nama");
        txt_stok.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Stok");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new com.raven.swing.ButtonGradient();
        btn_batal = new com.raven.swing.ButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        cb_satuan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("MASTER > Barang > Tambah");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM TAMBAH BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_simpan.setText("SIMPAN");
        btn_simpan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Stok");

        cb_satuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cb_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satuan", "Pack", "Renteng" }));
        cb_satuan.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Nama");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Satuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama)
                            .addComponent(txt_stok)
                            .addComponent(cb_satuan, 0, 240, Short.MAX_VALUE))
                        .addGap(0, 82, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (btn_simpan.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_simpan.getText().equals("PERBARUI")) {
//            perbaruiData();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        if (btn_simpan.getText().equals("SIMPAN")) {
            resetForm();
        } else if (btn_simpan.getText().equals("PERBARUI")) {
            dispose();
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormBarang formbarang = new FormBarang();
                FormInputBarang dialog = new FormInputBarang(new javax.swing.JFrame(), true, 1, null, formbarang);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ButtonGradient btn_batal;
    private com.raven.swing.ButtonGradient btn_simpan;
    private javax.swing.JComboBox<String> cb_satuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_stok;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        List<ModelBarang> list = servis.tampilData();
        tblModel.setData(list);
    }

    private void resetForm() {
        txt_nama.setText("");
        txt_stok.setText("");
        cb_satuan.setSelectedIndex(0);
    }

    private boolean validasiInput() {
        boolean valid = false;

        if (txt_nama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Nama kosong");
        } else if (txt_stok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
            System.out.println("Validasi gagal: Username kosong");
        } else {
            valid = true;
        }

        return valid;
    }

    private void simpanData() {
        if (validasiInput()) {
            String nama = txt_nama.getText();
            String satuan = cb_satuan.getSelectedItem().toString();
            double stok = Double.parseDouble(txt_stok.getText());

            ModelBarang model = new ModelBarang();
            model.setNama_barang(nama);
            model.setSatuan(satuan);
            model.setStok(stok);
         
            servis.tambahData(model); // Menambahkan data ke database
            tblModel.insertData(model); // Menambahkan data ke tabel model
            refreshTable(); // Menyegarkan tabel
            resetForm(); // Reset form input
            dispose(); // Menutup form
        }
    }

    private void dataTable() {
        btn_simpan.setText("PERBARUI");

        idBarang = barang.getIdBarang();
        String stok = String.valueOf(barang.getStok());
        
        txt_nama.setText(barang.getNama_barang());
        txt_stok.setText(stok);
        cb_satuan.setSelectedItem(barang.getSatuan());

        jLabel1.setText("MASTER > Barang > Perbarui");
        jLabel2.setText("PERBARUI DATA BARANG");
    }

//    private void perbaruiData() {
//        String nama = txt_nama.getText();
//        String rfid = txt_rfid.getText(); // Tidak mengubah RFID yang sudah ada
//        String barangname = txt_stok.getText();
//        String alamat = txt_alamat.getText();
//        String no_telepon = txt_notelp.getText();
//        String Role = cb_satuan.getSelectedItem().toString();
//
//        ModelUser model = new ModelUser();
//        model.setIdUser(idUser); // Pastikan ID sudah di-set
//        model.setNama(nama);
//        model.setRfidUid(rfid); // Jangan mengubah RFID
//        model.setUsername(barangname);
//        model.setNo_telepon(no_telepon);
//        model.setAlamat(alamat);
//        model.setRole(Role);
//
//        servis.perbaruiData(model); // Perbarui data di database
//        tblModel.updateData(row, model); // Perbarui data di tabel model
//        resetForm(); // Reset form input
//        dispose(); // Menutup form
//    }
    
    void refreshTable() {
        loaddata();
    }

  
}
