/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.form;

import com.app.config.ConnectionDB;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.BoxLayout;
import javax.swing.border.TitledBorder;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Rohim
 */
public class FormDashboard extends javax.swing.JPanel {

    private javax.swing.JPanel panelKonten;
    private com.toedter.calendar.JDateChooser dateAwal, dateAkhir;
    private javax.swing.JButton btnFilter;
    private javax.swing.JTable table;
    private javax.swing.table.DefaultTableModel model;
    private JTable tabelRinci;
    private DefaultTableModel modelRinci;
    private JLabel labelTotal;

    /**
     * Creates new form FormDashboard
     */
    public FormDashboard() {
        initComponents();
        custompanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void custompanel() {
        panel1 = new com.raven.swing.Panel();
        panel2 = new com.raven.swing.GradientPanel(new Color(255, 105, 180), new Color(255, 182, 193)); // Merah muda cerah
        panel3 = new com.raven.swing.GradientPanel(new Color(144, 238, 144), new Color(173, 255, 47)); // Hijau cerah
        panel4 = new com.raven.swing.GradientPanel(new Color(255, 165, 0), new Color(255, 218, 185)); // Oranye cerah
        panel5 = new com.raven.swing.GradientPanel(new Color(109, 157, 197), new Color(163, 201, 226)); // Biru gradasi sesuai gambar

        // Set border melengkung untuk setiap panel
        int cornerradius = 20;
        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE, 0, true));
        panel3.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE, 0, true));
        panel4.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE, 0, true));
        panel5.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE, 0, true));

        // Optional jika menggunakan setRound dari class custom
        panel2.setCornerRadius(20);
        panel3.setCornerRadius(20);
        panel4.setCornerRadius(20);
        panel5.setCornerRadius(20);

        // Gunakan padding dengan EmptyBorder
        panel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel1.setLayout(new GridLayout(1, 4, 20, 0)); // spasi antar panel 20px horizontal

        panel1.add(panel2);
        panel1.add(panel3);
        panel1.add(panel4);
        panel1.add(panel5);

        // Tata letak untuk panel2 (Jumlah Produk)
        JPanel contentPanel2 = new JPanel(new GridBagLayout());
        contentPanel2.setOpaque(false);
        GridBagConstraints gbc2 = new GridBagConstraints();
        gbc2.insets = new Insets(5, 5, 5, 5);
        gbc2.anchor = GridBagConstraints.CENTER;

        JLabel icon2 = new JLabel("\uD83D\uDED2"); 
        icon2.setForeground(Color.WHITE);
        icon2.setFont(new Font("Bebas Neue", Font.PLAIN, 30));
        gbc2.gridx = 0;
        gbc2.gridy = 0;
        gbc2.gridwidth = 1;
        contentPanel2.add(icon2, gbc2);

        JLabel title2 = new JLabel("Jumlah Produk");
        title2.setForeground(Color.WHITE);
        title2.setFont(new Font("Bebas Neue", Font.BOLD, 35));
        gbc2.gridx = 1;
        gbc2.gridy = 0;
        gbc2.gridwidth = 1;
        contentPanel2.add(title2, gbc2);

        JLabel value2 = new JLabel("0");
        value2.setForeground(Color.WHITE);
        value2.setFont(new Font("Bebas Neue", Font.BOLD, 60));
        gbc2.gridx = 0;
        gbc2.gridy = 1;
        gbc2.gridwidth = 2;
        contentPanel2.add(value2, gbc2);

        JLabel detail2 = new JLabel("Complete & Quality Choice");
        detail2.setForeground(Color.WHITE);
        detail2.setFont(new Font("SansSerif", Font.PLAIN, 16));
        gbc2.gridx = 0;
        gbc2.gridy = 2;
        gbc2.gridwidth = 2;
        contentPanel2.add(detail2, gbc2);

        panel2.setLayout(new BorderLayout());
        panel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel2.add(contentPanel2, BorderLayout.CENTER);

        // Tata letak untuk panel3 (Jumlah Supplier)
        JPanel contentPanel3 = new JPanel(new GridBagLayout());
        contentPanel3.setOpaque(false);
        GridBagConstraints gbc3 = new GridBagConstraints();
        gbc3.insets = new Insets(5, 5, 5, 5);
        gbc3.anchor = GridBagConstraints.CENTER;

        JLabel icon3 = new JLabel("\uD83C\uDFED"); 
        icon3.setForeground(Color.WHITE);
        icon3.setFont(new Font("Bebas Neue", Font.PLAIN, 30));
        gbc3.gridx = 0;
        gbc3.gridy = 0;
        gbc3.gridwidth = 1;
        contentPanel3.add(icon3, gbc3);

        JLabel title3 = new JLabel("Jumlah Supplier");
        title3.setForeground(Color.WHITE);
        title3.setFont(new Font("Bebas Neue", Font.BOLD, 35));
        gbc3.gridx = 1;
        gbc3.gridy = 0;
        gbc3.gridwidth = 1;
        contentPanel3.add(title3, gbc3);

        JLabel value3 = new JLabel("0");
        value3.setForeground(Color.WHITE);
        value3.setFont(new Font("Bebas Neue", Font.BOLD, 60));
        gbc3.gridx = 0;
        gbc3.gridy = 1;
        gbc3.gridwidth = 2;
        contentPanel3.add(value3, gbc3);

        JLabel detail3 = new JLabel("Trusted & Professional Partner");
        detail3.setForeground(Color.WHITE);
        detail3.setFont(new Font("SansSerif", Font.PLAIN, 16));
        gbc3.gridx = 0;
        gbc3.gridy = 2;
        gbc3.gridwidth = 2;
        contentPanel3.add(detail3, gbc3);

        panel3.setLayout(new BorderLayout());
        panel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel3.add(contentPanel3, BorderLayout.CENTER);

        // Tata letak untuk panel4 (Jumlah Pembelian)
        JPanel contentPanel4 = new JPanel(new GridBagLayout());
        contentPanel4.setOpaque(false);
        GridBagConstraints gbc4 = new GridBagConstraints();
        gbc4.insets = new Insets(5, 5, 5, 5);
        gbc4.anchor = GridBagConstraints.CENTER;

        JLabel icon4 = new JLabel("\uD83D\uDCB3"); 
        icon4.setForeground(Color.WHITE);
        icon4.setFont(new Font("Bebas Neue", Font.PLAIN, 30));
        gbc4.gridx = 0;
        gbc4.gridy = 0;
        gbc4.gridwidth = 1;
        contentPanel4.add(icon4, gbc4);

        JLabel title4 = new JLabel("Jumlah Pembelian");
        title4.setForeground(Color.WHITE);
        title4.setFont(new Font("Bebas Neue", Font.BOLD, 35));
        gbc4.gridx = 1;
        gbc4.gridy = 0;
        gbc4.gridwidth = 1;
        contentPanel4.add(title4, gbc4);

        JLabel value4 = new JLabel("0");
        value4.setForeground(Color.WHITE);
        value4.setFont(new Font("Bebas Neue", Font.BOLD, 60));
        gbc4.gridx = 0;
        gbc4.gridy = 1;
        gbc4.gridwidth = 2;
        contentPanel4.add(value4, gbc4);

        JLabel detail4 = new JLabel("Quick and easy purchase");
        detail4.setForeground(Color.WHITE);
        detail4.setFont(new Font("SansSerif", Font.PLAIN, 16));
        gbc4.gridx = 0;
        gbc4.gridy = 2;
        gbc4.gridwidth = 2;
        contentPanel4.add(detail4, gbc4);

        panel4.setLayout(new BorderLayout());
        panel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel4.add(contentPanel4, BorderLayout.CENTER);

        // Tata letak untuk panel5 (Jumlah User)
        JPanel contentPanel5 = new JPanel(new GridBagLayout());
        contentPanel5.setOpaque(false);
        GridBagConstraints gbc5 = new GridBagConstraints();
        gbc5.insets = new Insets(5, 5, 5, 5);
        gbc5.anchor = GridBagConstraints.CENTER;

        JLabel icon5 = new JLabel("\uD83D\uDC65"); 
        icon5.setForeground(Color.WHITE);
        icon5.setFont(new Font("Bebas Neue", Font.PLAIN, 30));
        gbc5.gridx = 0;
        gbc5.gridy = 0;
        gbc5.gridwidth = 1;
        contentPanel5.add(icon5, gbc5);

        JLabel title5 = new JLabel("Jumlah User");
        title5.setForeground(Color.WHITE);
        title5.setFont(new Font("Bebas Neue", Font.BOLD, 35));
        gbc5.gridx = 1;
        gbc5.gridy = 0;
        gbc5.gridwidth = 1;
        contentPanel5.add(title5, gbc5);

        JLabel value5 = new JLabel("0");
        value5.setForeground(Color.WHITE);
        value5.setFont(new Font("Bebas Neue", Font.BOLD, 60));
        gbc5.gridx = 0;
        gbc5.gridy = 1;
        gbc5.gridwidth = 2;
        contentPanel5.add(value5, gbc5);

        JLabel detail5 = new JLabel("supports Login with RFID");
        detail5.setForeground(Color.WHITE);
        detail5.setFont(new Font("SansSerif", Font.PLAIN, 16));
        gbc5.gridx = 0;
        gbc5.gridy = 2;
        gbc5.gridwidth = 2;
        contentPanel5.add(detail5, gbc5);

        panel5.setLayout(new BorderLayout());
        panel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel5.add(contentPanel5, BorderLayout.CENTER);

        // Ambil data dari database
        try {
            Connection conn = ConnectionDB.getConnection();
            String sqlProduk = "SELECT COUNT(*) AS total FROM tbl_master_barang";
            String sqlSupplier = "SELECT COUNT(*) AS total FROM tbl_supplier";
            String sqlPembelian = "SELECT COUNT(*) AS total FROM tbl_pembelian";
            String sqlUser = "SELECT COUNT(*) AS total FROM tbl_user";

            PreparedStatement psProduk = conn.prepareStatement(sqlProduk);
            PreparedStatement psSupplier = conn.prepareStatement(sqlSupplier);
            PreparedStatement psPembelian = conn.prepareStatement(sqlPembelian);
            PreparedStatement psUser = conn.prepareStatement(sqlUser);

            ResultSet rsProduk = psProduk.executeQuery();
            ResultSet rsSupplier = psSupplier.executeQuery();
            ResultSet rsPembelian = psPembelian.executeQuery();
            ResultSet rsUser = psUser.executeQuery();

            if (rsProduk.next()) {
                value2.setText(String.format("%,d", rsProduk.getInt("total")));
            }
            if (rsSupplier.next()) {
                value3.setText(String.format("%,d", rsSupplier.getInt("total")));
            }
            if (rsPembelian.next()) {
                value4.setText(String.format("%,d", rsPembelian.getInt("total")));
            }
            if (rsUser.next()) {
                value5.setText(String.format("%,d", rsUser.getInt("total")));
            }

            rsProduk.close();
            rsSupplier.close();
            rsPembelian.close();
            rsUser.close();
            psProduk.close();
            psSupplier.close();
            psPembelian.close();
            psUser.close();
            conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data\n" + ex.getMessage());
        }

        // Panel konten bawah (bisa scroll atau isi lain)
        panelKonten = new javax.swing.JPanel();
        panelKonten.setBackground(Color.WHITE);
        panelKonten.setPreferredSize(new java.awt.Dimension(0, 400)); // contoh isi konten
        panelKonten.setLayout(new java.awt.BorderLayout());

        // Komponen filter
        JPanel panelAtas = new JPanel(new BorderLayout());
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDateFormatString("p");
        dateChooser.setPreferredSize(new Dimension(200, 45)); // Enlarged size for better visibility

        JLabel dateLabel = new JLabel("Filter Tanggal:");
        dateLabel.setFont(new Font("SansSerif", Font.BOLD, 16)); // Enhanced font for label
        panelAtas.add(dateLabel, BorderLayout.WEST);

        JPanel panelFilter = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 0));
        panelFilter.add(dateChooser);
        panelAtas.add(panelFilter, BorderLayout.CENTER);

        dateChooser.addPropertyChangeListener("date", evt -> {
            if (dateChooser.getDate() != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
                String tanggal = sdf.format(dateChooser.getDate());

                try {
                    modelRinci.setRowCount(0);
                    Connection conn = ConnectionDB.getConnection();
                    String sql = "SELECT * FROM tbl_penjualanrinci WHERE id_penjualan LIKE ?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, "REF" + tanggal + "%");
                    ResultSet rs = ps.executeQuery();
                    int no = 1;
                    double total = 0;
                    while (rs.next()) {
                        String idPenjualan = rs.getString("id_penjualan");
                        String namaBarang = rs.getString("nama_barang");
                        double qty = rs.getDouble("qty");
                        String satuan = rs.getString("satuan");
                        double harga = rs.getDouble("harga");
                        double nilai = rs.getDouble("nilai");
                        total += nilai;

                        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
                        symbols.setGroupingSeparator('.');
                        DecimalFormat df = new DecimalFormat("#,###", symbols);
                        df.setParseIntegerOnly(true);
                        String formattedHarga = df.format((long) harga);
                        String formattedNilai = df.format((long) nilai);

                        modelRinci.addRow(new Object[]{
                            no++, idPenjualan, namaBarang, qty, satuan, formattedHarga, formattedNilai
                        });
                    }

                    DecimalFormatSymbols symbolsTotal = new DecimalFormatSymbols();
                    symbolsTotal.setGroupingSeparator('.');
                    symbolsTotal.setDecimalSeparator(',');
                    DecimalFormat dfTotal = new DecimalFormat("#,###", symbolsTotal);
                    dfTotal.setParseIntegerOnly(true);
                    labelTotal.setText("Total: Rp " + dfTotal.format((long) total));
                    rs.close();
                    ps.close();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Gagal memuat data\n" + ex.getMessage());
                }
            }
        });

        String[] kolom = {"No", "ID Penjualan", "Nama Barang", "Qty", "Satuan", "Harga"};
        modelRinci = new DefaultTableModel(null, kolom) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabelRinci = new JTable(modelRinci);
        tabelRinci.setRowHeight(25);
        tabelRinci.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelRinci.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabelRinci.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelRinci.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabelRinci.getColumnModel().getColumn(3).setPreferredWidth(40);
        tabelRinci.getColumnModel().getColumn(4).setPreferredWidth(60);
        tabelRinci.getColumnModel().getColumn(5).setPreferredWidth(80);

        tabelRinci.setShowGrid(true);
        tabelRinci.setGridColor(Color.BLACK);

        JTableHeader header = tabelRinci.getTableHeader();
        header.setBackground(new Color(70, 130, 180));
        header.setForeground(Color.WHITE);
        header.setFont(new Font("SansSerif", Font.BOLD, 18));

        JScrollPane scrollTabel = new JScrollPane(tabelRinci);
        scrollTabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.BLACK), "Rincian Transaksi", TitledBorder.CENTER, TitledBorder.TOP, new Font("SansSerif", Font.BOLD, 26)));

        labelTotal = new JLabel("Total: Rp 0");
        labelTotal.setFont(new Font("SansSerif", Font.BOLD, 24));
        labelTotal.setHorizontalAlignment(SwingConstants.RIGHT);
        JPanel panelTotal = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 0));
        panelTotal.add(labelTotal);
        panelAtas.add(panelTotal, BorderLayout.EAST);
        panelAtas.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        JPanel wrapper = new JPanel();
        wrapper.setLayout(new BoxLayout(wrapper, BoxLayout.Y_AXIS));
        wrapper.add(panelAtas);
        wrapper.add(scrollTabel);

        setLayout(new BorderLayout());
        add(wrapper, BorderLayout.CENTER);

        panelKonten.add(panelAtas, BorderLayout.NORTH);
        panelKonten.add(scrollTabel, BorderLayout.CENTER);

        panel1.setPreferredSize(new Dimension(0, 200));
        panel1.setMaximumSize(new Dimension(Integer.MAX_VALUE, 150));

        wrapper.setLayout(new javax.swing.BoxLayout(wrapper, javax.swing.BoxLayout.Y_AXIS));
        wrapper.add(panel1);
        wrapper.add(panelKonten);

        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(wrapper);
        scroll.setBorder(null);
        scroll.getVerticalScrollBar().setUnitIncrement(16);

        setLayout(new java.awt.BorderLayout());
        add(scroll, java.awt.BorderLayout.CENTER);

        loadSemuaData();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new com.raven.swing.Panel();
        panel2 = new com.raven.swing.Panel();
        panel3 = new com.raven.swing.Panel();
        panel4 = new com.raven.swing.Panel();
        panel5 = new com.raven.swing.Panel();

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadSemuaData() {
        try {
            modelRinci.setRowCount(0);
            Connection conn = ConnectionDB.getConnection();
            String sql = "SELECT * FROM tbl_penjualanrinci";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            int no = 1;
            double total = 0;
            while (rs.next()) {
                String idPenjualan = rs.getString("id_penjualan");
                String namaBarang = rs.getString("nama_barang");
                double qty = rs.getDouble("qty");
                String satuan = rs.getString("satuan");
                double harga = rs.getDouble("harga");
                double nilai = rs.getDouble("nilai");
                total += nilai;

                modelRinci.addRow(new Object[]{
                    no++, idPenjualan, namaBarang, qty, satuan, harga, nilai
                });
            }
            labelTotal.setText("Total: Rp " + String.format("%,.0f", total));
            rs.close();
            ps.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Panel panel1;
    private com.raven.swing.Panel panel2;
    private com.raven.swing.Panel panel3;
    private com.raven.swing.Panel panel4;
    private com.raven.swing.Panel panel5;
    // End of variables declaration//GEN-END:variables
}
